### ISSUE TITLE
requirements.yml refers to an obsole role

### ISSUE THREAD

**Issue by clevesque** [cloudera-labs/ansible-runner#92]
cldr-runner/base/requirements.yml refers to an obsolete role

roles:
  - name: geerlingguy.postgresql
    version: 2.2.0
  - src: https://github.com/dbeech/ansible-role-mysql
    version: master

The role dbeech/ansible-role-mysql does not work with mySQL 8....only with and older 5.7 era mysql

I would suggest
  - src: https://github.com/clevesque/ansible-role-mysql
    version: master

**Comment by wmudge** [comment]
Agreed. I would actually like to remove this dependency completely. I think using this role is overkill for our needs.

**Comment by wmudge** [comment]
Updated the requirements via #77
